spring:
  application:
    name: dine-in-order-api

#DATASOURSE CONFIGURATION

  datasource:
    url: jdbc:mysql://localhost:3306/dine_in_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8082